-- Phase 2: Database Schema

-- 1. Queue Table
CREATE TABLE public.queue (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_date date NOT NULL DEFAULT current_date, -- for daily reset
  token_number integer NOT NULL, -- incremental for token_date
  full_token text NOT NULL, -- e.g., "2025-11-20-012"
  name text NOT NULL,
  phone text,
  email text,
  reason text,
  status text NOT NULL DEFAULT 'waiting', -- waiting | called | done | skipped | cancelled
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  estimated_wait_seconds integer, -- optional cache of estimate when joined
  served_at timestamptz
);

-- Indexes for Queue
CREATE UNIQUE INDEX idx_queue_token_date_number ON public.queue (token_date, token_number);
CREATE INDEX idx_queue_status ON public.queue (status);

-- 2. Service Metrics Table (for averaging service time)
CREATE TABLE public.service_metrics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  served_at timestamptz NOT NULL,
  service_duration_seconds integer NOT NULL, -- seconds between called and done
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Enable RLS (Row Level Security)
ALTER TABLE public.queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_metrics ENABLE ROW LEVEL SECURITY;

-- Grant usage to anon/authenticated roles (basic setup, refined in Phase 4)
GRANT SELECT, INSERT, UPDATE ON public.queue TO anon, authenticated, service_role;
GRANT SELECT, INSERT ON public.service_metrics TO anon, authenticated, service_role;
